<!-- changed url with my ip address -->
server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://44.195.247.21:1001/api/v1/ 
    shoe:
      path: /shoe/**
      url: http://44.195.247.21:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://44.195.247.21:1003
    cart:
      path: /cart/**
      url: http://44.195.247.21:1004/api/v1
